### ISSUE TITLE
xdg compliance in linux

### ISSUE THREAD

**Issue by pirate486743186** [phoboslab/wipeout-rewrite#47]
it would be nice to follow the linux user folders standard.

the xdg standard
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

In short:

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
> 
> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> 
> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

here, you only care about config

**Comment by phoboslab** [comment]
Related PR: https://github.com/phoboslab/wipeout-rewrite/pull/10 – though [SDL_GetPrefPath](https://wiki.libsdl.org/SDL2/SDL_GetPrefPath) doesn't seem to honor `$XDG_CONFIG_HOME` (yet). I don't think I want to go down this road and figure out the correct save path on each platform by myself. `SDL_GetPrefPath()` seems to be "good enough".

**Comment by samueldr** [comment]
It uses `DATA_HOME` rather than `CONFIG_HOME`.

 - https://github.com/libsdl-org/SDL/blob/3b1d1e4e31ba17eba2271f34a6c1db4ba1a883c0/src/filesystem/unix/SDL_sysfilesystem.c#L261-L269

For things like save games, it should be the preferred location.

Though there is always a bit of an ambiguity with those paths and not moving files all over the place.
