### ISSUE TITLE
Framerate on Korodera track is awful

### ISSUE THREAD

**Issue by tjrileywisc** [phoboslab/wipeout-rewrite#61]
I regularly get around 100 fps on most tracks, but Korodera (especially near the start) is really laggy. I barely get 30 fps there.

**Comment by phoboslab** [comment]
What hardware are you running on?

https://github.com/phoboslab/wipeout-rewrite/commit/ecf1e635082188d3294e10abb255128204854127 should help a little, but to truly fix this we'd need to create OpenGL ready triangles just once on object load (and possibly upload them to the GPU) instead of creating them anew for every frame.

Not sure if I want to go down this road, because it will make the renderer implementation more complicated, which makes it harder to create new rendering backends...

**Comment by tjrileywisc** [comment]
I saw it both running on several platforms (WASM and ubuntu WSL) - but the fixes did help. The framerate on Korodera is at about 70 fps now, which is good enough I think.

**Comment by phoboslab** [comment]
Oh, you probably got the software renderer in the browser then. Sadly, WebGL is still blacklisted for a lot of GPUs. Happy to hear that it works a bit better now :]
